### PR TITLE
Fix/30 update ring leds for new pcb design

### LINKED ISSUE #30: Update ring leds for new PCB design
The new PCB design has 64 LED's, this makes the current animations look bad. Also the first LED is now positioned at the top instead of on the left, which means that the angles are off by 90/270 degrees.

### PR DESCRIPTION
**Pull request by SquaredPotato**
Closes #30

### CODE REVIEW

**Review by abrondijk — APPROVED** [review]

File: components/ring_lights/src/effects.cpp [hunk 1]
```diff
@@ -105,13 +105,26 @@ void effects::percent(rgb_t (& buffer)[NUM_LEDS], effect_msg& msg) {
 	int_fast16_t correct_end = start + (total_width * (percent));
 	correct_end %= 360;
 
+    double degree_per_percent = (total_width / 100.0);
+
+    // The vast majority of the LED's will be set using this colour, so avoid recalculating it for every LED
```
Comment (Ricovl) [inline components/ring_lights/src/effects.cpp:110]: *color

**Review by Ricovl — APPROVED** [review]
Very nice. Keep up the good work!
